[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    arduino-libraries/ArduinoIoTCloud @ 2.9.0
    arduino-libraries/Arduino_ConnectionHandler @ 1.2.0

lib_ignore =
    WiFiNINA
    Arduino_SpiNINA